configfile: 'config.yaml'

include: 'rules/genotyping.smk'
include: 'rules/ont-alignment.smk'
include: 'rules/prepare-vcf.smk'
include: 'rules/bubble-tagging.smk'
include: 'rules/common-rules.smk'
include: 'rules/get-sample-list.smk'
include: 'rules/self-genotyping.smk'
include: 'rules/callset-comparisons.smk'

wildcard_constraints:
    sample='|'.join(samples)

rule all:
    input:
        expand('results/{callset}/genotypes/multisample-multiallelic.vcf.gz', callset = [c for c in config['callsets'].keys()]),
        expand('results/{callset}/genotypes/multisample-biallelic.vcf.gz', callset = [c for c in config['callsets'].keys()]),
        expand('results/{callset}/self-genotyping/concordance-{representation}/summary_{min_af}-{max_af}.tsv', 
                    callset = [c for c in config['callsets'].keys()], 
                    representation=['biallelic', 'multiallelic'], 
                    min_af=['0', '0.05', '0.1', '0.2'], 
                    max_af=['1']),
        #expand('results/{callset}/callset-comparison/out-graph/{sample}-{min_af}-{max_af}/intersection-upsetplot.pdf', callset = [c for c in config['callsets'].keys()], sample = config['hgsvc_samples'], min_af=['0'], max_af=['1']),
        #expand('results/{callset}/callset-comparison/in-graph/HG01258-{min_af}-{max_af}/intersection-upsetplot.pdf', callset = [c for c in config['callsets'].keys()], min_af=['0'], max_af=['1']),
        #expand('results/{callset}/truvari-comparison/out-graph/{sample}-{source}-{min_af}-{max_af}/summary.json', callset = [c for c in config['callsets'].keys()], sample = config['hgsvc_samples'], source = ['pangenie'], min_af=['0'], max_af=['1']),
        #expand('results/{callset}/truvari-comparison-lenient/out-graph/{sample}-{source}-{min_af}-{max_af}/summary.json', callset = [c for c in config['callsets'].keys()], sample = config['hgsvc_samples'], source = ['pangenie'], min_af=['0'], max_af=['1']),
        #expand('results/{callset}/truvari-comparison/in-graph/HG01258-{source}-{min_af}-{max_af}/summary.json', callset = [c for c in config['callsets'].keys()], source = ['pangenie', 'pangenie_panel', 'giggles_panel'], min_af=['0'], max_af=['1']),
        